name: example
description: Charts-Flutter Demo
dependencies:
  charts_flutter:
    path: ../
  cupertino_icons: ^0.1.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  meta: ^1.1.1
  intl: ^0.17.0 
flutter:
  uses-material-design: true

dependency_overrides:
  charts_common:
    path: ../../charts_common